# Name of your site (displayed in the header)
name: SonDelVent

# Short bio or description (displayed in the header)
description: Música mediterranea en una noche estrellada

cover: música mediterranea en una noche estrellada<br>Aromas de jazmín que vuelan al son de una guitarra flamenca
minibio: Grupo de música mediterranea desde Barcelona.<br>Sensualidad, alegría y fiesta con el sabor especial del flamenco y la fusión latina. Una vida entera dedicada al oficio de las canciones avalan este espectáculo que hace reír, sentir y soñar.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://{{ site.baseurl }}/hipertextos/brand/icon.jpg

phone1: 661269611
phone2: 661269611
contratacion: SonDelVent

# HOME page
home_video: LBtiJlI9U0w

# MEDIA page
video1: LBtiJlI9U0w
video2: J5s2AgwXyqI
video3: g-PS8ftx5ME
video4: yGY6jr4DlMs
video5:
video6:
video7:
video8:
video9:

# CONTACTO page
biotitle: Música mediterranea en una noche estrellada
bio: Grupo de música mediterranea desde Barcelona.<br>Sensualidad, alegría y fiesta con el sabor especial del flamenco y la fusión latina. Una vida entera dedicada al oficio de las canciones avalan este espectáculo que hace reír, sentir y soñar.
presstitle: Zona de Prensa
prensa: música mediterranea en una noche estrellada<br>Aromas de jazmín que vuelan al son de una guitarra flamenca
d_press: Archivo de Prensa
u_press: /download/name.pdf
d_rider: Rider Técnico
u_rider: /download/name.pdf
d_fotos: Fotografias
u_fotos: /download/name.zip
d_all: Bajar todo
u_all: /download/name.zip

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: sondelvent@gmail.com
  facebook: sondelvent
  flickr:
  github:
  instagram: sondelvent
  linkedin:
  pinterest:
  rss: rss
  twitter: sondelvent
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UC9D8DWb0Xu1KI-9ncz4YvNw
  googleplus: # anything in your profile username that comes after plus.google.com/  

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.sondelvent.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Defaults
defaults:
  -
    scope:
      path: "assets/fotos"
    values:
      image: true